language: python
python:
  - "3.6"

before_script:
  - createuser -U besevic -d travis_ci_test --superuser
  - pip install -r requirements.txt

branches:
  only:
    - master

services:
  - postgresql

addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
env:
  global:
    - PGPORT=5432
    - DJANGO_SETTINGS_MODULE="oc_projet_13.settings.travis"

script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test
