language: python
python:
  - "3.6"

before_script:
  - pip install -r requirements.txt

branches:
  only:
    - master

env: DJANGO_SETTINGS_MODULE="oc_projet_13.settings.travis"

dist: xenial

script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test