language: python
python:
  - "3.6"

before_script:
  - createuser -U besevic -d travis_ci_test --superuser
  - pip install -r requirements.txt

branches:
  only:
    - master

services:
  - postgresql

dist: xenial
addons:
  postgresql: "9.5"

env: DJANGO_SETTINGS_MODULE="oc_projet_13.settings.travis"

script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test
