
language: python
python:
  - "3.6.3"

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -c 'create database test;' -U postgres
  - psql -c "CREATE USER besevic WITH PASSWORD 'unpassword';" -U postgres
  - psql -c "ALTER USER besevic CREATEDB;" -U postgres
  - pip install -r requirements.txt

branches:
  only:
    - staging

env: DJANGO_SETTINGS_MODULE="oc_projet_13.settings.travis"

services:
  - postgresql

script:
  - python manage.py makemigrations
  - python manage.py migrate
- python manage.py test