# Generated by Django 2.2.2 on 2019-06-23 08:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogue', '0002_auto_20190623_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('too_late_accepted_payment', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CommandeMeeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('date_meeting', models.DateTimeField()),
                ('qrcode', models.ImageField(blank=True, null=True, upload_to='qrcode/%Y/%m/%d/')),
                ('from_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_commande', to='ventes.Commande')),
                ('to_meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_meeting', to='catalogue.Meeting')),
            ],
            options={
                'unique_together': {('from_commande', 'to_meeting', 'date_meeting')},
            },
        ),
        migrations.AddField(
            model_name='commande',
            name='meetings',
            field=models.ManyToManyField(through='ventes.CommandeMeeting', to='catalogue.Meeting'),
        ),
        migrations.AddField(
            model_name='commande',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
