# Generated by Django 2.1.7 on 2019-03-10 10:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0002_auto_20190310_1130'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommandeMeeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('date_meeting', models.DateTimeField()),
                ('from_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_commande', to='ventes.Commande')),
                ('to_meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_meeting', to='catalogue.Meeting')),
            ],
        ),
        migrations.AddField(
            model_name='commande',
            name='meetings',
            field=models.ManyToManyField(through='ventes.CommandeMeeting', to='catalogue.Meeting'),
        ),
        migrations.AddField(
            model_name='commande',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='commandemeeting',
            unique_together={('from_commande', 'to_meeting', 'date_meeting')},
        ),
    ]
