# Generated by Django 2.1.7 on 2019-03-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandemeeting',
            name='date_meeting',
            field=models.DateTimeField(),
        ),
    ]
