# Generated by Django 2.1.7 on 2019-03-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandemeeting',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='qrcode/%Y/%m/%d/'),
        ),
    ]
