# Generated by Django 2.1.7 on 2019-03-09 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_auto_20190301_1556'),
        ('ventes', '0002_auto_20190308_1351'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commandemeeting',
            unique_together={('from_commande', 'to_meeting', 'date_meeting')},
        ),
    ]
