# Generated by Django 2.1.7 on 2019-05-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0003_commande_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='too_late_accepted_paymeny',
            field=models.BooleanField(default=True),
        ),
    ]
