# Generated by Django 2.1.7 on 2019-03-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0003_auto_20190309_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
