# Generated by Django 2.1.7 on 2019-05-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0005_auto_20190525_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='too_late_accepted_payment',
            field=models.BooleanField(default=False),
        ),
    ]
