# Generated by Django 2.1.7 on 2019-05-25 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0006_auto_20190525_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='too_late_accepted_payment',
            new_name='too_late_attempt_payment',
        ),
    ]
