# Generated by Django 2.1.7 on 2019-03-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_auto_20190310_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='meeting/%Y/%m/%d/'),
        ),
    ]
