# Generated by Django 2.1.7 on 2019-02-26 19:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_auto_20190226_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='space_available',
        ),
        migrations.AddField(
            model_name='place',
            name='space_available',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
