# Generated by Django 2.1.7 on 2019-02-28 12:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_auto_20190226_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='price',
            field=models.FloatField(default=15.0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(150)]),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='artists',
            field=models.ManyToManyField(blank=True, to='catalogue.Artist'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='authors',
            field=models.ManyToManyField(blank=True, to='catalogue.Author'),
        ),
    ]
