# Generated by Django 2.1.7 on 2019-03-01 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_auto_20190228_1312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ('title',)},
        ),
    ]
