# Generated by Django 2.1.7 on 2019-02-26 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swingtime', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='occurrence',
            options={'base_manager_name': 'objects', 'ordering': ('start_time', 'end_time'), 'verbose_name': 'occurrence', 'verbose_name_plural': 'occurrences'},
        ),
        migrations.AddField(
            model_name='eventtype',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_set', to='swingtime.EventType'),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='sib_order',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
