# Generated by Django 2.1.7 on 2019-05-26 08:45

from django.db import migrations
import swingtime.fields


class Migration(migrations.Migration):

    dependencies = [
        ('swingtime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='recurrences',
            field=swingtime.fields.RecurrenceField(blank=True, default=None, null=True),
        ),
    ]
