# Generated by Django 2.1.7 on 2019-02-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swingtime', '0004_remove_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='reserved_place',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
