# Generated by Django 2.1.7 on 2019-03-01 14:58

from django.db import migrations
import swingtime.fields


class Migration(migrations.Migration):

    dependencies = [
        ('swingtime', '0005_occurrence_reserved_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occurrence',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='recurrences',
            field=swingtime.fields.RecurrenceField(default=None, null=True),
        ),
        migrations.DeleteModel(
            name='Occurrence',
        ),
    ]
